### ISSUE TITLE
WSL 2 support

### ISSUE THREAD

**Issue by avi12** [WarningImHack3r/npm-update-dependencies#108]
### What problem are you trying to solve?

Since I have a bug when trying to get Vite to run Svelte on my Windows 10 machine, someone recommended running the setup on WSL 2, in my case I have Ubuntu 22.04.3 LTS
It works surprisingly well (except for hot module replacement, but that's another issue)
Now the biggest issue is seeing a bunch of packages being reported as not installed by this plugin, even though they were installed in the Linux environment using PNPM

### Describe the solution you’d like

Add optional support for it via the settings section

### Describe any alternatives you’ve also considered

Currently, I can only ignore the warnings produced by the plugin as I haven't seen any setting related to WSL or Linux

### Additional info
Plugin version: 2.3.2

**Comment by WarningImHack3r** [comment]
Hi there, thanks for that idea!
Can you elaborate on what you mean by "being reported as not installed by this plugin"? Which warnings are you talking about?

**Comment by avi12** [comment]
![image](https://github.com/WarningImHack3r/npm-update-dependencies/assets/6422804/6fc112f0-f9da-491c-a3d6-2f9f6c942a71)

**Comment by WarningImHack3r** [comment]
Hmm this is not from my plugin, it’s from the IDE itself

**Comment by WarningImHack3r** [comment]
Did you follow the [official docs](https://www.jetbrains.com/help/idea/how-to-use-wsl-development-environment-in-product.html)?

Anyways, if something’s wrong with my plugin with WSL, I’d be happy to help!

**Comment by avi12** [comment]
Never mind then, time to file a [bug report](https://youtrack.jetbrains.com/issue/WEB-67498/PNPM-module-scanning-for-WSL-2) 😅 
Sorry for bothering you!

**Comment by avi12** [comment]
> Did you follow the [official docs](https://www.jetbrains.com/help/idea/how-to-use-wsl-development-environment-in-product.html)?

I admittedly haven't
I quickly read it through and when I tried to select the project from the WSL end, I got
![image](https://github.com/WarningImHack3r/npm-update-dependencies/assets/6422804/c0bf16c2-22eb-4941-ba9b-6537aace56c3)

**Comment by WarningImHack3r** [comment]
Alright, don’t hesitate to open as needed!

**Comment by WarningImHack3r** [comment]
Yep, the /mnt folder is where you Windows drive is mounted, just unfold the `c` folder to see the contents of you `C:`

**Comment by avi12** [comment]
That's the thing, somehow the WebStorm file picker cannot access it

**Comment by WarningImHack3r** [comment]
Oh yes i didn’t see the unfolded arrow, my bad
Yeah it’s indeed weird…

**Comment by WarningImHack3r** [comment]
@avi12 as per their answer, I recommend you try with raw `npm` or `bun` in the meantime as they fix it

Then keep me updated if everything works fine with my plugin!

**Comment by avi12** [comment]
Thanks all for your help, but I insist on using PNPM 
It's faster and more convenient for me 
Talking about Ben, WebStorm [doesn't have an official support for it yet](https://youtrack.jetbrains.com/issue/WEB-63031/Add-support-for-Bun-runtime-and-package-manager)
