### ISSUE TITLE
`"deprecated": false` considers the dependency deprecated

### ISSUE THREAD

**Issue by mohamed155** [WarningImHack3r/npm-update-dependencies#122]
### What is the issue?

The package recognizes "@syncfusion/ej2-angular-popups": "^26.2.11" as deprecated, and that's likely because the plugin only checks on the deprecated property but not its value since this package has "deprecated": "false" in its package.json file

### What are the steps to reproduce this issue?

Use the plugin in webstorm or any jetbrains IDE then in any npm project, install `@syncfusion/ej2-angular-popups`. The plugin will mark this package as deprecated while it's not.

### What were you expecting to happen?

The plugin reads the "deprecated" property value, to avoid mark packages as deprecated while it's not.

### What OS are you experiencing the problem on?

Linux

### Additional platform information

Using webstorm 2024.2.1

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
@mohamed155 thanks for opening this issue! That’s indeed what’s happening, but what even is the use case of an explicit "false" value? 😅
Anyways, I’m pushing a fix in a few hours!
