### ISSUE TITLE
[crash] ExternalToolPass:

### ISSUE THREAD

**Issue by mcccarthy** [WarningImHack3r/npm-update-dependencies#139]
### What is the issue?

?

### What are the steps to reproduce this issue?

?

### What were you expecting to happen?

?

### Paste any relevant logs, error output, etc.

```shell
com.intellij.diagnostic.PluginException: annotator: com.github.warningimhack3r.npmupdatedependencies.ui.annotation.PackageManagerAnnotator@4b909094 (class com.github.warningimhack3r.npmupdatedependencies.ui.annotation.PackageManagerAnnotator) [Plugin: com.github.warningimhack3r.npmupdatedependencies]
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.PackageManagerAnnotator.collectInformation(PackageManagerAnnotator.kt:147)
	at com.github.warningimhack3r.npmupdatedependencies.ui.annotation.PackageManagerAnnotator.collectInformation(PackageManagerAnnotator.kt:27)
	... 27 more
```

### What OS are you experiencing the problem on?

Linux

### Additional platform information

Build version: WebStorm 2024.2.2 Build: #WS-242.22855.79 September 18, 2024
JRE: 21.0.3+13-b509.15, JetBrains s.r.o.
JVM: 21.0.3+13-b509.15, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Linux 6.8.0-45-generic (amd64)

=== Plugins ===
Custom plugins: [NPM Update Dependencies (3.2.0), Codeium: AI Autocomplete and Chat for Python, JS, Java, Go... (1.20.2), Key Promoter X (2024.2.0), .env files support (2024.2.1), Prisma ORM (242.22855.32)]
Disabled plugins:[JetBrains AI Assistant (242.22855.75)]

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Thanks for reporting! 3.2.1 is already being verified as we speak and should be available later today or tomorrow. Sorry for the inconvenience!
