### ISSUE TITLE
Incorrect detection of the latest version when there are multiple support versions

### ISSUE THREAD

**Issue by IvanSavoskin** [WarningImHack3r/npm-update-dependencies#150]
### What is the issue?

If the library supports several versions at once (for example 4.x and 5.x), the plugin incorrectly determines whether there is an update

### What are the steps to reproduce this issue?

The express library currently supports versions 4.x and 5.x. The latest version is 4.21.1 (it is also marked as latest on GitHub). But the latest version is 5.0.1.
When installing version 4.21.0 in package.json, the plugin will offer an update to 4.21.1. But if you install version 5.0.0, then an update to 5.0.1 will not be offered

### What were you expecting to happen?

It is expected that if version 5.0.0 is set in package.json, the plugin will offer an update to version 5.0.1

### Paste any relevant logs, error output, etc.

```shell
npm outdated
Package                           Current  Wanted  Latest  Location                                       
express                             5.0.1   5.0.1  4.21.1  node_modules/express
```

### What OS are you experiencing the problem on?

Windows, macOS, Linux

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
(More precisely, in this case, it only happens when a 4.x version is released _after_ the initial 5.x release)
