### ISSUE TITLE
Cannot update package

### ISSUE THREAD

**Issue by gander** [WarningImHack3r/npm-update-dependencies#152]
### What is the issue?

Cannot update plugin. Nor uninstall or disable. 

### What are the steps to reproduce this issue?

Click update plugin

### What were you expecting to happen?

Update plugin and ready to work

### Paste any relevant logs, error output, etc.

```shell
Empty range: request 'https://downloads.marketplace.jetbrains.com/files/21105/618341/npm-update-dependencies-3.4.0.zip' range ''
```

### What OS are you experiencing the problem on?

Linux

### Additional platform information

Linux Mint 22

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Hi there, seems like a connection issue between you and JetBrains’ servers? It’s weird you can’t uninstall it though.
I can’t do anything about that though, you should open a ticket on their side I guess

**Comment by gander** [comment]
I had a problem with updating this package multiple times before, so I couldn't disable or uninstall it, and I don't even remember how I dealt with it. I think I managed to uninstall and reinstall it, and it was a great update, but I thought it had been resolved, but apparently not.

**Comment by WarningImHack3r** [comment]
Honestly I don't think I can do anything about that unfortunately, I'll close this issue, let me know when you managed to update!
