### ISSUE TITLE
Confusing banner with only unmaintained dependencies

### ISSUE THREAD

**Issue by avi12** [WarningImHack3r/npm-update-dependencies#154]
### What is the issue?

Incorrectly shows
![image](https://github.com/user-attachments/assets/a50a8f9c-b4f2-47cc-a560-70036f92186a)

### What are the steps to reproduce this issue?

In the `package.json`, add
```json
{
  "dependencies": {
    "chartjs-adapter-date-fns": "^3.0.0"
  }
}
```
In the [NPM page listing](https://npm.im/chartjs-adapter-date-fns), it's not indicated as deprecated, but the plugin will mistakenly think it's deprecated

### What were you expecting to happen?

The detection of deprecation should be fixed

### What OS are you experiencing the problem on?

Windows

### Additional platform information

A workaround that I found is using
```json
{
  "dependencies": {
    "chartjs-adapter-date-fns": "github:chartjs/chartjs-adapter-date-fns"
  }
}
```
though interestingly enough, `pnpm i` won't trigger the creation of `node_modules/chartjs-adapter-date-fns/dist/...`
Only if I use an explicit version number, it creates the `dist/...`

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Hi there, it's not what you think it is!
This is the new key feature from 3.3.0: you can now be warned about dependencies that haven't been updated for a while.
If you hover over this dependency, the popup will tell you that.

This feature is enabled by default and set to one year before considering a dependency as outdated: you can choose to either not include outdated dependencies in the banner or to tweak/disable the feature altogether, all from the plugin settings!

**Comment by avi12** [comment]
I see
I think the language should be changed from "deprecated" to "hasn't been updated in a while", because I'd expect a dependency to be considered deprecated only if it's declared as such, like
![www npmjs com_package_source-sans-pro](https://github.com/user-attachments/assets/10a81bff-3a5c-4bd0-bf4a-c7212b6f6758)

**Comment by WarningImHack3r** [comment]
You can exclude "outdated" packages from the banner in the settings if you don't like this

Also, did you check what the "unmaintained" package says on hovering? Do you also see that the highlighting is different from regular and actually deprecated packages?

**Comment by avi12** [comment]
> did you check what the "unmaintained" package says on hovering?

I didn't

> Do you also see that the highlighting is different from regular and actually deprecated packages?

I don't tend to use packages declared as deprecated in NPM, so I'm only encountered the warning top bar as presented in the original post

Anyway, your feature intention is good but the missing part is the UX and I believe that all you need to do is change
https://github.com/WarningImHack3r/npm-update-dependencies/blob/1692675894894c5b0af776851a2ec16687e624d2/src/main/kotlin/com/github/warningimhack3r/npmupdatedependencies/ui/banner/DeprecationBanner.kt#L71-L75

to say "1 package hasn't been updated in a long time. Remove it to avoid issues" / "You have 2 packages that haven't been updated in a long time. Remove them to avoid issues"

**Comment by WarningImHack3r** [comment]
Although you can disable this feature, I can agree on the fact that the banner message is not clear in this specific case.
Is it okay for you if I just tweak it?

**Comment by avi12** [comment]
I mean it is your plugin, do whatever you want lol
I'm just here as a user giving feedback

**Comment by WarningImHack3r** [comment]
I meant is the core of your issue the correctness of the banner message? Would you consider it solved if I tweaked it?

**Comment by avi12** [comment]
The issue I mentioned is that the banner says "deprecated" while what it actually means is that the package hasn't been updated in a long time, since a deprecation in NPM means a different thing than "hasn't been updated lately"

**Comment by WarningImHack3r** [comment]
It does that because the banner originally exists for deprecated dependencies, and as the same actions/considerations could be applied to "unmaintained" dependencies, I didn't bother tweaking the very message.

**Comment by avi12** [comment]
I see, so I'd appreciate it if you could tweak the message such that for NPM deprecations it would say "deprecated" and if the package hasn't been updated in a long time it would say that
Also, it would be nice if I could selectively display the banner, for each scenario

**Comment by WarningImHack3r** [comment]
I'll separate "unmaintained" dependencies into their own banner. More customizable and fixes the message issue.
