### ISSUE TITLE
Auto Fix on save is broken?

### ISSUE THREAD

**Issue by mallowigi** [WarningImHack3r/npm-update-dependencies#155]
### What is the issue?

I don't know if it's due to the latest version but the latest version adds an 1 on every save if I select "auto-fix on save":

https://github.com/user-attachments/assets/997484d1-7fb2-4edf-84f3-2622d44efb41

### What are the steps to reproduce this issue?

1. Download latest version
2. Enable Auto Fix on Save
3. Save
4. Complain

### What were you expecting to happen?

.

### What OS are you experiencing the problem on?

macOS

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Hi there, yes I’m aware of this; it’s not related to this specific feature but on the overall way to detect and replace an update that I messed up in the latest release

It’s fixed in 1692675894894c5b0af776851a2ec16687e624d2 and will be part of the next update, sorry for the inconvenience!
