### ISSUE TITLE
Low contrast text in on top banners

### ISSUE THREAD

**Issue by rakleed** [WarningImHack3r/npm-update-dependencies#160]
### What is the issue?

Low contrast text on top banners.

<details><summary>Screenshots ↓</summary>

Light theme:
![CleanShot 2024-11-15 at 13 58 09](https://github.com/user-attachments/assets/fcf41521-823a-4815-94d6-41033b3deed5)

Dark theme:
![CleanShot 2024-11-15 at 14 03 54](https://github.com/user-attachments/assets/3ecc5de5-035d-40d3-bc97-d3bbe7041440)

Built-in WebStorm banners for example in light theme:
![CleanShot 2024-11-04 at 12 47 46](https://github.com/user-attachments/assets/5669cb74-0d79-49a1-b26e-933e998c42d7)

And dark theme:
![CleanShot 2024-10-29 at 23 08 26](https://github.com/user-attachments/assets/68e62389-5940-4401-84ed-e65e50ebafaf)

</details>

### What are the steps to reproduce this issue?

1. Open `package.json` with deprecated (`@babel/plugin-proposal-private-methods`) and outdated (`html2canvas `) packages
2. Wait until banners on top appear

### What were you expecting to happen?

The text has high contrast and is easy to read.

I think for light theme you should make the background lighter, and for dark theme you should make the text white (not gray and not transparent) and maybe make the background darker.

### What OS are you experiencing the problem on?

macOS

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Hi there, good catch! Unfortunately, I don't have much control over this: I can only specify a background color from a defined JB-provided set, and that's it.
I just changed the blue one to a default one, but I'd like to keep a yellowish color for deprecations.
