### ISSUE TITLE
How to build plugin?

### ISSUE THREAD

**Issue by rakleed** [WarningImHack3r/npm-update-dependencies#161]
### Issue type

Lack of documentation

### Description

Could you add information on how to build the plugin in the README?

I can look at https://github.com/WarningImHack3r/npm-update-dependencies/blob/main/.github/workflows/build.yml, but it would be much more convenient to have a detailed and understandable description.

### Special case

- [X] This is not a bug nor a feature request, I can't use other templates

**Comment by WarningImHack3r** [comment]
I'll consider it and see if it's easily doable
