### ISSUE TITLE
plugin do not wait for (npm | yarn) install to finish to start scan for dependencies

### ISSUE THREAD

**Issue by axel7083** [WarningImHack3r/npm-update-dependencies#58]
### What is the issue?

When opening and running `(yarn | npm) install` on very large project (E.g. [ProtonMail/WebClients](https://github.com/ProtonMail/WebClients)). The install process is **very** long by default, but running it with the plugin make it even longer. Thus leading to a complete freeze of the IDE.

### What are the steps to reproduce this issue?

- Clone large repository with many packages (more than one `package.json`)
- Run `(npm | yarn) install`
- Wait ?

### What were you expecting to happen?

Wait for the yarn install process to finish to start analyzing dependencies

### What OS are you experiencing the problem on?

Windows

### Additional platform information

WebStorm 2023.3.2

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Hi there, thanks for reporting!
The scanning process only occurs when you have a `package.json` open or changed, which is not a direct cause of a `<manager> i`.

I suggest you to `<manager> i` first, then open your `package.json` file, or at least not open it while you're `<manager> i`ing.

If despite all that you encounter a slowness in the scanning process freezing your IDE with an idling npm, then please reopen and update your issue. Thanks!
