### ISSUE TITLE
2.1.3 bricks my IDE

### ISSUE THREAD

**Issue by kitsunde** [WarningImHack3r/npm-update-dependencies#72]
### What is the issue?

My WebStorm gets stuck as "Scanning for deprecations 0/53" without progress after upgrading. I have a repo with multiple packacage.json. Restarting does nothing, disabling and re-enabling does nothing. The UI becomes completely unresponsive. My repo has 1 private package.

### What are the steps to reproduce this issue?

Unclear I simply upgraded and it stopped working.

### What were you expecting to happen?

My UI to continue to work.

### What OS are you experiencing the problem on?

macOS

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
> My WebStorm gets stuck as "Scanning for deprecations 0/53" without progress after upgrading.

How long did you wait? The scan should start at most a few seconds after being at 0.

> Unclear I simply upgraded and it stopped working.

Can you try this new version and tell me if it changes something? [npm-update-dependencies-2.1.4.jar.zip](https://github.com/WarningImHack3r/npm-update-dependencies/files/14222126/npm-update-dependencies-2.1.4.jar.zip)
