### ISSUE TITLE
[crash] com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.github.warningimhack3r.npmupdatedependencies.ui.actions.MainActionGroup' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.warningimhack3r.npmupdatedependencies]

### ISSUE THREAD

**Issue by CrazyBoy49z** [WarningImHack3r/npm-update-dependencies#79]
### What is the issue?

Crash

### What are the steps to reproduce this issue?

-

### What were you expecting to happen?

-

### What OS are you experiencing the problem on?

macOS

### Additional platform information

Build version: PhpStorm 2024.1 Beta Build: #PS-241.14494.28 March 7, 2024
JRE: 17.0.10+8-b1207.6, JetBrains s.r.o.
JVM: 17.0.10+8-b1207.6, OpenJDK 64-Bit Server VM, JetBrains s.r.o.
Operating System: Mac OS X 12.7.3 (x86_64)

=== Plugins ===
Custom plugins: [PDF Viewer (0.15.0), Battery Status (2.3.1), WakaTime (14.3.11), Indent Rainbow (2.2.0), Clock Widget (2.0.0), CPU Usage Indicator (1.18.0-IJ2023), CMD Support (1.0.5), String Manipulation (9.12.0), PhpStorm Help (241.14494.28), Naming Is Hard (1.5.0), Json Parser (1.7.1), Json Helper (1.3.2), Unicode Escaper (1.0.2), Database Navigator (3.4.3073.0), Catppuccin Theme (3.2.3), Rainbow CSV (2.0.2), Settings Repository (Deprecated) (241.14494.17), Toolset (2024.3.1), NPM Update Dependencies (2.1.3), Open Regex101 (0.2), AI Assistant (241.14494.33), W3C Validators (241.14494.17), Sass Lint (1.1.2), Extra ToolWindow Colorful Icons (1.33.0), Endpoints (241.14494.28), JsonToAnyLanguage (2023.1.6), WebAssembly (241.14494.17), JsonToTypeScript (2023.1.2), Mnemonic Keymap (2023.1.0), json2ts (1.0.12), JavaFX Runtime for Plugins (1.0.4), LiveTemplatePreview (0.3), License Template (2.0.0), .ignore (4.5.2), AI Commits (1.6.0), GitHub Copilot (1.5.0.5192-nightly), Alpine.js Support (v0.4.2), JSLint (202.3), Spy-js (241.14494.17), GitToolBox (500.2.0+233), Atom Material Icons (95.0.0), Collector (0.5.0), PHP Hammer (0.30.0), PHP Advanced AutoComplete (1.1.0), .env files support (2024.1), PhpClean (2023.12.17), Php Inspections (EA Extended) (5.0.0.0), PHP Toolbox (6.2.0), PHP Annotations (9.4.0), Symfony Support (2023.1.265), Rainbow Brackets Lite - Free and OpenSource (1.1.0), PHPStan Toolbox (0.0.7), Laravel Idea (8.1.2.241), Color Highlighter (18.0.0), Translation (3.5.6), Better Highlights (2024.1.9)]
Disabled plugins:[Easy Code Screenshots (1.4.4), Hunspell (241.14494.28), InlineProblems (0.5.1), ExcelEditor (2023.11.1-222.233), SVGA Support (1.0.9), ChatWindow (1.1.25), Space (241.14494.17), PHPUnit code coverage (0.5.0), AI Coding Assistant (1.2.22), Automatic Power Saver (3.2.2), NetBeans Keymap (241.14494.28), Diff / Patch File Support (2.1.13), Eclipse Keymap (241.14494.28), LabelTranslate (1.3-SNAPSHOT), Key Promoter X (2023.3.0), Presentation Assistant (1.0.10), Gherkin (241.14494.28), Vagrant (241.14494.28), OpenAPI Specifications (241.14494.28), Kubernetes (241.8102.131), Qodana (241.14494.28), Cucumber.js (241.14494.28), Next.js (241.14494.28), Polymer & Web Components (241.14494.28), Karma (241.14494.28), Node.js Remote Interpreter (241.14494.28), Angular (241.14494.28), Import from Postman Collections (1.0.5), DQL (241.14494.28), Snyk Security - Code, Open Source, Container, IaC Configurations (2.6.1), Drupal (241.14494.28), WordPress (241.14494.28), Behat Support (241.14494.28), Codeception Framework (241.14494.28), i18n Ally (1.4.2.1), Joomla! (241.14494.28)]

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Hi there, thanks for reporting! I didn't get any issue reported from automatic plugin checker for 2024.1 but I'll check if I can fix that without compromising support for older versions.
That's really weird that is did actually _crash_ and not simply warned you though...

**Comment by WarningImHack3r** [comment]
Hi there @CrazyBoy49z, can you try out [this build](https://github.com/WarningImHack3r/npm-update-dependencies/actions/runs/8287578987/artifacts/1327582623) by installing it from disk and confirm me that the issue is fixed?

**Comment by CrazyBoy49z** [comment]
> Hi there @CrazyBoy49z, can you try out [this build](https://github.com/WarningImHack3r/npm-update-dependencies/actions/runs/8287578987/artifacts/1327582623) by installing it from disk and confirm me that the issue is fixed?

Fixed

**Comment by WarningImHack3r** [comment]
Great! Pushing the update :)
