### ISSUE TITLE
Ignore dependency version

### ISSUE THREAD

**Issue by Tsyklop** [WarningImHack3r/npm-update-dependencies#85]
### What problem are you trying to solve?

I have **@fingerprintjs/fingerprintjs** dependency. And I need only 3.4.2 version (4+ version paid for commercial use).

And I can't use 'Update all', because it update fingerprintjs dependency.

### Describe the solution you’d like

Do not update some dependencies.
RMB - Ignore. Like this.

**Comment by WarningImHack3r** [comment]
Hi, thanks for your suggestions!
This feature has been suggested within [a review](https://plugins.jetbrains.com/plugin/21105-npm-update-dependencies/reviews#review=98051), and I'm actively working on it!
The idea is simple, but it requires a lot of changes/new stuff in my code as I want to make it as good as possible.

As this requires a bunch of work and I'm also working on multiple projects in parallel it can take a few weeks to get dropped, but I'll be as quick as possible :)
