### ISSUE TITLE
Are you been hacked? NMP Update Dependencies Plugin - 2.1.4 WarningImHack3r

### ISSUE THREAD

**Issue by HomeOfSourceCode** [WarningImHack3r/npm-update-dependencies#91]
### Issue type

Problem

### Description

Dear Support,

one of our developer downloaded a plugin from your site:
https://plugins.jetbrains.com/plugin/21105-npm-update-dependencies
Version 2.1.4
After installing, the plugin shown a very strange comment, see screenshot. Are you been hacked?

![image](https://github.com/WarningImHack3r/npm-update-dependencies/assets/33092270/11e0ebbc-b262-4ee0-b208-a8d473b97edd)
 
evosoft Cybersecurity Team

### Special case

- [X] This is not a bug nor a feature request, I can't use other templates

**Comment by WarningImHack3r** [comment]
Hi there, it seems like it has been uninstalled by the IDE during a batch update process, as I pushed an update yesterday (2.1.4 is not the latest anymore). It’s probably an IDE bug.
I’ve already seem similar issues with different plugins on my own.
Rest assured that everything is fine and under my control so you can safely reinstall it.
You can inspect the code directly on this repo.

I’ll stay available if you need more info, and wait for your agreement to proceeding with closing this issue.

**Comment by WarningImHack3r** [comment]
OP didn't reply after 2 weeks, closing until they reply and need to reopen.
